name: Run ESLint
run-name: ${{ github.actor }} is running ESLint
on: [push]
jobs:
  check-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run lint
